import { Inter } from 'next/font/google';
import './globals.css';
import MainLayout from '@/components/MainLayout';

// Menginisialisasi font Inter dengan subset latin
const inter = Inter({ subsets: ['latin'] });

// Metadata untuk aplikasi
export const metadata = {
  title: 'Create Next App', // Judul aplikasi
  description: 'Generated by create next app', // Deskripsi aplikasi
};

// Fungsi RootLayout yang membungkus konten dengan MainLayout
export default function RootLayout({ children }) {
  return <MainLayout>{children}</MainLayout>; // Mengembalikan komponen MainLayout dengan children
}
